pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        exclusiveContent {
            forRepository {
                maven { url = uri('https://maven.mozilla.org/maven2') }
            }
            filter { includeGroupByRegex('org\\.mozilla\\..*') }
        }
    }
}

rootProject.name = 'xanh-browser'
include ':app'
include ':backup-core'
include ':sync-core'
